### ISSUE TITLE
Wallet does not connect to IOS expo go app

### ISSUE THREAD

**Issue by kodisj** [Sphereon-Opensource/ssi-mobile-wallet#11]
Scanning the bar code says, No usable data found.
![image](https://user-images.githubusercontent.com/2355397/205989929-f8583412-96ea-4ccc-957c-fd0245be1370.png)

**Comment by nklomp** [comment]
Hi @kodisj 

Since we are still very much in a development phase (pre-alpha!), we expect developers to have the expo go client installed on their mobile device. Once installed it would recognize the above QR code and open up the app.
https://expo.dev/client

As mentioned, be aware that the wallet still is in an alpha stage. We expect a version somewhere early next year, that allows you to recieve and present credentials. Right now you can only receive credentials from the issuers listed in the repository basically.

Although most of the sharing functionality is there, we are working hard on updated protocols/clients at the lower levels and we will integrate these really soon.

**Comment by kodisj** [comment]
I did install expo client on my mobile, I scanned the barcode, it said data
not usable.  How to run the wallet on my iPhone is the question?

-KODIS

**Comment by nklomp** [comment]
Sorry  didn't notice you were talking about IOS. 

Hmzz, we have an outstanding issue with not building on IOS that we need to fix ASAP. On thursday several developers will be in the office and then we could do a bit of testing ourselves with Xcode/Mac and and an iPhone.

cc: @sanderPostma @BtencateSphereon @SPodshivalin

**Comment by kodisj** [comment]
Sounds good.  The issue is the barcode generated when run, it applies to
both android and ios I guess, any reason why you have gone with expo ?

**Comment by nklomp** [comment]
Reason was that it provided a clean app initially. But we soon ran into low-level requirements that forced us to eject anyway. So there are still quite a few expo deps in there, as some of them do provide some nice functionality.

The QR code does work on Android btw.

**Comment by kodisj** [comment]
Got it.  I am highly impressed with your work.  Keep up the good work.  I
will be evaluating more closely going forward.

-Kodis

**Comment by kodisj** [comment]
> Reason was that it provided a clean app initially. But we soon ran into low-level requirements that forced us to eject anyway. So there are still quite a few expo deps in there, as some of them do provide some nice functionality.
> 
> The QR code does work on Android btw.

Even in android, the QR code does not seem to work.  it points to "com.sphereon.ssi.wallet://expo-development-client/?url=http%3A%2F%2F6a-j76.anonymous.ssi-mobile-wallet.exp.direct%3A80",   which is invalid, i guess.

**Comment by nklomp** [comment]
Sorry. One of our devs who would take a look at it, got ill the other day. 

Could you try the `yarn android` or `yarn ios` tasks respectively instead of `yarn start`. The difference is that these tasks will actually install the app on your phone, if connected with a USB cable. 

The URL you see in the QR is indeed one of the app, so it would never know how to handle these, without having the app actually installed.

**Comment by nklomp** [comment]
Okay, given the develop branch is working on both iOS and Android builds from multiple different installations and given we have updated the README, I am going to close this one.

In case the problem persist, please create a new ticket.
